config/routes.rb
Rails.application.routes.draw do

	root 'shows#index'
  resources :favorites
  resources :channels
  resources :shows
  get '/search', to: 'shows#search'
  devise_for :users, :controllers =>{ registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	has_many :shows
	validates :name, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
	belongs_to :channel
	has_many :favorites
	has_many :users, through: :favorites

	validates :title, presence: true
	validates :time, presence: true

	scope :search, -> (query) { joins(:channel).where("lower(title) LIKE ? OR lower(channels.name) LIKE ?", "%" + query.downcase + "%", "%" + query.downcase + "%") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :favorites
  has_many :shows, through: :favorites
  

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to shows_path, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to shows_path, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_show
  
    def create
      favorite = Favorite.new(show_id: @show.id, user_id: current_user.id)
      if favorite.save
        redirect_to shows_path, notice: 'Show has been favorited...!'
      end
    end
    
    def destroy
      Favorite.where(show_id: @show.id, user_id: current_user.id).first.destroy
      redirect_to shows_path, notice: 'Show has been removed from favorites...!'
    end
    
    private
    
    def set_show
      @show = Show.find(params[:show_id] || params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	private
	
	def sign_up_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to shows_path, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to shows_path, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @shows = Show.search(params[:query])
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:title, :description, :time, :channel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/channels/_form.html.erb
<div class="column is-half ">
  <article class="media box">
    <div class="media-content">
      

      <%= simple_form_for(@channel) do |f| %>
        <div class="field">
          <%= f.label :name, class: "label" %>
          <div class="control">            
            <%= f.text_field :name, class: "input", placeholder: "Enter Name" %><br>            
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= f.submit class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", shows_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </article>
</div>

app/views/channels/edit.html.erb
<% content_for :content do %> 
	<%= render 'form', channel: @channel %>
<% end %>

app/views/channels/index.html.erb
<% content_for :content do %>  
  <div class="column is-half ">
      


    <% @channels.each do |channel| %>
      <div class="box">
        <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(channel.name, size: 64) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <strong><%= channel.name %></strong>
              
            </div>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to 'Edit', edit_channel_path(channel) %>
              <%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </nav>
        </article>
      </div>
    <% end %>
  </div>
<% end %>

app/views/channels/new.html.erb
<% content_for :content do %> 
	<%= render 'form', channel: @channel %>
<% end %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>

app/views/favorites/_form.html.erb
<%= simple_form_for(@favorite) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :show_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.show_id %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Show:</strong>
  <%= @favorite.show_id %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChannelDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
	  	<div class="notification is-primary global-notification">
	  		<p class="notice"><%= notice %></p>  		
	  	</div>
  	<% end %>

  	<% if flash[:alert] %>
	  	<div class="notification is-danger global-notification">
	  		<p class="alert"><%= alert %></p>  		
	  	</div>
  	<% end %>
  	<nav class=" navbar is-info">
  		<div class="navbar-brand">
	  		<%= link_to root_path, class: "navbar-item" do %>
	  			<h1 class="title is-5">Channel APP</h1>
	  		<% end %>
	  		<div class="navbar-burger burger" data-taget="navbarExample">
	  			<span></span>
	  			<span></span>
	  			<span></span>
	  		</div>
	  	</div>

	  	<div id="navbarExample" class="navbar-menu">
	  		<div class="navbar-end">
	  			<div class="field is-grouped">
	  				<p class="control">
	  					<% if user_signed_in? %>
	  						<%#= link_to(current_user.name, edit_registration_path, class: "button is-info") %>  
	  					<% end %>
	  				</p>
	  				<p class="control">
	  					<%#= link_to "New Tweet", root_path, class: "button is-info is-inverted" %>
	  					<% if user_signed_in? %>
						  
						  <%= link_to('Logout', destroy_user_session_path, class: "button is-info",method: :delete) %>        
						  
						<% else %>
						  
						  <%= link_to('Login', new_user_session_path, class: "button is-info") %>  
						  
						<% end %>
	  				</p>
	  			</div>
	  		</div>
	  	</div>
  	</nav>
    <% if current_user %>
  	<section class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <nav class="panel">
              <p class="panel-heading">Profile</p>
              <div class="panel-block">
                <article class="media">
                  <div class="media-left">
                    <figure class="image is64x64">
                      <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.email) %>
                    </figure>
                  </div>
                  <div class="media-content">
                    <div class="content">
                      <p>
                        <strong><%= current_user.email %></strong>
                      </p>
                    </div>
                  </div>
                </article>
              </div>
              <div class="panel-block">
                <div class="level is-mobile">
                  <div class="level-item has-centered-text">
                    <div>
                      <p class="heading"><h1><%= link_to "Browse Shows", shows_path %></h1></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-block">
                <div class="level is-mobile">
                  <div class="level-item has-centered-text">
                    <div>
                      <p class="heading"><h1><%= link_to "Add New Show", new_show_path, :method => "get", class: "btn btn-info btn-block" %></h1></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-block">
                <div class="level is-mobile">
                  <div class="level-item has-centered-text">
                    <div>
                      <p class="heading"><h1><%= link_to "Browse Channels", channels_path %></h1></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-block">
                <div class="level is-mobile">
                  <div class="level-item has-centered-text">
                    <div>
                      <p class="heading"><h1><%= link_to "Add New Channel", new_channel_path, :method => "get", class: "btn btn-info btn-block" %></h1></p>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </div>
          <%= yield :content %>
          <div class="column">
            <nav class="panel">
              <p class="panel-heading">
                Advertisement
              </p>
            </nav>
          
            <div class="panel-block">
              <article class="media">
                <div class="media-left">
                  
                </div>
                <div class="media-content">
                  <div class="content">
                    <p>
                      
                    </p>
                  </div>
                </div>
              </article>
            </div>
          </div>
        </div>    
      </div>
    </section>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<div class="column is-half ">
  <article class="media box">
    <div class="media-content">
      <% if @show.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
            <% @show.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for(show) do |f| %>
        <div class="field">
          <%= f.label :title, class: "label" %>
          <div class="control">            
            <%= f.text_field :title, class: "input", placeholder: "Enter Title" %><br>            
          </div>
        </div>

        <div class="field">
          <%= f.label :channel, class: "label" %>
          <div class="control">
            <%= f.collection_select :channel_id, Channel.all, :id, :name, {:include_blank => true}, {class: "input"} %>
          </div>
        </div>

        
        <div class="field">
          <%= f.label :time, class: "label" %>
          <div class="control">            
            <%= f.text_field :time, class: "input", id: "datetimepicker",placeholder: "Enter Date and time in DD/MM/YYYY HH:MM" %>
          </div>
        </div>

        <%= f.hidden_field :created_by, value: current_user.id %>

        <div class="field">
          <%= f.label "Description", class: "label" %>
          <div class="control">
            <%= f.text_area :description, class:"textarea", placeholder: "Enter Discription" %><br>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= f.submit class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", shows_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </article>
</div>
<script>
  $('#datetimepicker').datetimepicker();
  $("#datetimepicker").keyup(function(){
    $("#datetimepicker").val("");
  });
</script>

app/views/shows/edit.html.erb
<% content_for :content do %> 
	<%= render 'form', show: @show %>
<% end %>

app/views/shows/index.html.erb
<% content_for :content do %>  
  <div class="column is-half ">
    <article class="media box">
      <div class="media-content">
        <%= form_tag("/search", method: "get") do %>
          <div class="field has-addons">
            <div class="control">
              <%= text_field_tag :query, "", class: "input", placeholder: "Find a Show" %>
            </div>
            <div class="control">
              <%= submit_tag "Search", class: "button is-info" %>
            </div>
          </div>
        <% end %>
      </div>
    </article>


    <% @shows.each do |show| %>
      <div class="box">
        <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(show.title, size: 64) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <strong><%= link_to show.title, show_path(show) %></strong>
              <small><%= show.channel.name %></small>
              <p><small><%= show.description %></small></p>
              <p><%= show.time.to_datetime.strftime("%a %d.%m.%Y") %> - <%= show.time.to_datetime.strftime("%I:%M %p") %> </p>
            </div>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <% unless current_user && current_user.favorites.exists?(id: show.id) %>
                <%= link_to favorites_path(show_id: show.id), method: :post, class: "level-item" do %>
                <!-- <span class="icon"><i class="fa fa-link" aria-hidden="true">Add to Faviriot</i></span> -->
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg>
                <% end %>
              <% else %>
                <%= link_to favorite_path(show), method: :delete do %>
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28v1c.563 0 .901.272 1.066.56.086.15.121.3.121.416 0 .12-.035.165-.04.17l-.354.353.353.354c.202.202.407.512.505.805.104.312.043.44-.005.488l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.415-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.353.352.373.714.267 1.021-.122.35-.396.593-.571.651-.653.218-1.447.224-2.11.164a8.907 8.907 0 0 1-1.094-.17l-.014-.004H9.62a.5.5 0 0 0-.595.643 8.34 8.34 0 0 1 .145 4.725c-.03.112-.128.215-.288.255l-.262.066c-.306.076-.642-.156-.667-.519-.075-1.081-.239-2.15-.482-2.85-.174-.502-.603-1.267-1.238-1.977C5.597 8.926 4.715 8.23 3.62 7.93 3.226 7.823 3 7.534 3 7.28V3.279c0-.26.22-.515.553-.55 1.293-.138 1.936-.53 2.491-.869l.04-.024c.27-.165.495-.296.776-.393.277-.096.63-.163 1.14-.163h3.5v-1H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                  </svg>
                <% end %>
              <% end %>
            </div>
          </nav>
        </article>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shows/new.html.erb
<% content_for :content do %> 
	<%= render 'form', show: @show %>
<% end %>